### PR TITLE
Server application written in PHP for plug-in compatibility feedback from Jenkins users

### PR DESCRIPTION
**Pull request by kinow**
This is a simple server application for storing user feedback about plug-in compatibility. It reports whether the plug-in is working or not with a certain Jenkins version. This way we can create the jelly/java part in Jenkins.

This application was written with Slim (for RESTful + Logging) and ActiveRecord (for ORM).

You can see the server running at http://www.tupilabs.com/infra-rating/ (try /ratings or /pluginStatus for JSON output). 

And a sample application with a form to submit plug-in feedback and query the plug-in statuses is available at http://www.tupilabs.com/infra-rating/sample_app/.

This server application seems to be quite different than the previous plugin rating application. Not sure if it would be better to create a separate repository for this application, or replace it with this pull request.

### CODE REVIEW

**Comment by kohsuke** [comment]
OMG, 40K LoC addition!

I feel really bad that we left this unattended for 2 years. Since this isn't compatible with the current version, I think it's best to put this in a separate repository. Are you still interested in taking this forward? Does it help if we set you up with the system access so that you can deploy this by yourself?

**Comment by jakesylvestre** [comment]
I'd think it would need updates with the incompatibilty

**Comment by kinow** [comment]
Hi, the code can be simplified and polished, use newer PHP, updated UI, etc. I'll try to update the PR, fix the broken link and attach some screenshots.

**Comment by daniel-beck** [comment]
@kinow  I'm planning to look into integrating user feedback into Jenkins itself. We should probably coordinate our efforts.

**Comment by kinow** [comment]
Sure thing @daniel-beck. Let me know (here or in the dev-list) about what you have in mind, and I'll be happy if I can help in some way :+1:

**Comment by kinow** [comment]
Uh, probably won't have time to ever look at this code. I barely remembered creating the PR. Closing to avoid confusion :grimacing:

**Pull request closed without merging**
