### PR TITLE
[INFRA-957] Ask again if user specifies no issue reference when cloudy

### PR DESCRIPTION
**Pull request by daniel-beck**
@oleg-nenashev @orrc 

Not exactly [INFRA-957](https://issues.jenkins-ci.org/browse/INFRA-957), but let's hope this suffices.WDYT?

### CODE REVIEW

**Comment by daniel-beck** [comment]
@rtyler This change appears to not be deployed. How does that work?

**Comment by rtyler** [comment]
@daniel-beck The puppet agent on `rating.jenkins.io` had apparently died before @olblak's changes to monitoring the Puppet agent went through. I manually kicked the host and it is now running the latest container for this application

**Comment by daniel-beck** [comment]
@rtyler Is it possible there's no container with this change or something? Because https://rating.jenkins.io/rate/rate.js is still old.

**Comment by daniel-beck** [comment]
FTR two of the 'cloudy' votes for 2.37 are me :cry:

CC @oleg-nenashev who might care about changelog feedback.

**Comment by daniel-beck** [comment]
@oleg-nenashev FYI this has been deployed now after @rtyler fixed an infra issue.

**Pull request merged**
