### PR TITLE
Reference images from ci.jenkins.io

### PR DESCRIPTION
**Pull request by daniel-beck**

### CODE REVIEW

**Comment by rtyler** [comment]
@daniel-beck I noticed this recently, but the domain wasn't concerning so much as using Jenkins as a static asset server :frowning: 

Could I trouble you to just include the images in this repository directly? ci.jenkins.io shouldn't be bothered with rating traffic IMO

**Comment by daniel-beck** [comment]
@rtyler Sure, but could you merge and deploy to fix the current problem, and file an issue for that improvement?

**Comment by rtyler** [comment]
@daniel-beck yes I can but this is a tedious process to deploy, but whatever I guess

**Comment by daniel-beck** [comment]
@rtyler I'll be sure to wait a while before tackling this so it's worth the effort of deploying now 😉

**Comment by rtyler** [comment]
Deployed

**Pull request merged**
